name: Update Carta

on:
  schedule:
    - cron: "0 * * * *"   # cada hora
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Descargar agenda desde Google Sheets
        run: |
          curl -s "https://opensheet.vercel.app/1zWJII-FPLi7M19dgFIsU0WZDrJfs0CBncAjI_kEoyOM/Hoja1" > carta.json

      - name: Generar archivo de texto con todos los eventos
        run: |
          jq -r '.[] | " \(.usuario) -> \(.cantidad) "' carta.json > carta.txt

      - name: Commit y push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add carta.json carta.txt
          git commit -m "Lista actualizada automáticamente" || echo "No hay cambios"
          git push
